# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: harvardnlp
email: srush@seas.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Blog for the Harvard SEAS natural-language processing group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://harvardnlp.github.io" # the base hostname & protocol for your site
twitter_username: harvardnlp
github_username:  harvardnlp

# Build settings
markdown: kramdown
gems: ['jekyll/scholar']

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography/
  bibliography: ourwork.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"